'use client';
import { useState } from 'react';
import JSZip from 'jszip';

type Tab = 'summary' | 'insights' | 'transcript' | 'frames' | 'music';

interface ResultsDashboardProps {
  result: any;
  jobId: string;
  onReset: () => void;
}

// ── Helper: download any blob as a file ──────────────────────────────────────
function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

// ── Download all frames as a .zip ────────────────────────────────────────────
async function downloadFramesZip(frames: any[], apiUrl: string) {
  const zip = new JSZip();
  const folder = zip.folder('frames')!;

  await Promise.all(
    frames.map(async (frame: any, i: number) => {
      const res = await fetch(`${apiUrl}/frame/${frame.path}`);
      const blob = await res.blob();
      folder.file(`frame_${String(i + 1).padStart(3, '0')}_at_${Math.round(frame.timestamp)}s.jpg`, blob);
    })
  );

  const zipBlob = await zip.generateAsync({ type: 'blob' });
  downloadBlob(zipBlob, 'sakura_frames.zip');
}

// ── Download summary as a formatted text report ───────────────────────────────
function downloadSummaryReport(r: any) {
  let music = '\n🎵 MUSIC: Not detected';
  if (r.music?.detected) {
    const typeStr = r.music.inferred ? ' [AI Inferred]' : '';
    music = `\n🎵 MUSIC DETECTED${typeStr}\n  Song:   ${r.music.song_title}\n  Artist: ${r.music.artist}\n  Album:  ${r.music.album}\n  Genre:  ${r.music.genre}`;
    if (r.music.explanation) {
      music += `\n  AI Note: ${r.music.explanation}`;
    }
  }

  const mediaStr = r.referenced_media ? `\n🎬 REFERENCED MEDIA\n  ${r.referenced_media}\n` : '';

  const report = `
╔══════════════════════════════════════════════════════╗
║          SAKURA AI — VIDEO ANALYSIS REPORT           ║
╚══════════════════════════════════════════════════════╝

📊 OVERVIEW
  Duration:       ${r.duration_seconds}s
  Frames Sampled: ${r.frame_count}
  Words (audio):  ${r.word_count}
  Hook Score:     ${r.hook_score}/100
  Sentiment:      ${r.sentiment}
  Category:       ${r.content_category}
  Est. Watch:     ${r.estimated_watch_time}
  Audience:       ${r.target_audience}
${music}
${mediaStr}

📝 SUMMARY
${r.summary}

🏷️ TAGS
${(r.tags || []).map((t: string) => `  #${t}`).join('\n')}

📌 TOPICS
${(r.topics || []).map((t: string) => `  • ${t}`).join('\n')}

🪝 HOOK ANALYSIS
  Score: ${r.hook_score}/100
  ${r.hook_analysis}

💡 IMPROVEMENT SUGGESTIONS
${(r.suggestions || []).map((s: string, i: number) => `  ${i + 1}. ${s}`).join('\n')}

📜 TRANSCRIPT
${r.transcript || '(No audio detected)'}

─────────────────────────────────────────────────────
Generated by Sakura AI · ClipInsight · ${new Date().toLocaleDateString()}
`.trimStart();

  downloadBlob(new Blob([report], { type: 'text/plain' }), 'sakura_analysis_report.txt');
}

export default function ResultsDashboard({ result, jobId, onReset }: ResultsDashboardProps) {
  const [tab, setTab] = useState<Tab>('summary');
  const [downloading, setDownloading] = useState<'frames' | 'report' | 'pdf' | null>(null);
  const [shareToast, setShareToast] = useState('');

  const tabs: { key: Tab; label: string; icon: string; kanji: string }[] = [
    { key: 'summary',    label: 'Summary',    icon: '🌸', kanji: '要' },
    { key: 'insights',   label: 'Insights',   icon: '💡', kanji: '知' },
    { key: 'music',      label: 'Music',      icon: '🎵', kanji: '楽' },
    { key: 'transcript', label: 'Transcript', icon: '📜', kanji: '詩' },
    { key: 'frames',     label: 'Frames',     icon: '🎞', kanji: '映' },
  ];

  const r = result || {
    summary: 'Your AI-generated video analysis will appear here.',
    duration_seconds: 0, frame_count: 0, word_count: 0,
    sentiment: 'Neutral', sentiment_score: 0.5,
    hook_score: 0, tags: ['AI', 'Video', 'Analysis'],
    suggestions: ['Complete your first analysis to receive personalized suggestions.'],
    target_audience: 'General audience',
    transcript: '', frames: [], music: { detected: false },
  };

  const API = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000';

  const handleDownloadFrames = async () => {
    if (!r.frames?.length) return;
    setDownloading('frames');
    try {
      await downloadFramesZip(r.frames, API);
    } finally {
      setDownloading(null);
    }
  };

  const handleDownloadReport = () => {
    setDownloading('report');
    downloadSummaryReport(r);
    setDownloading(null);
  };

  const handleDownloadPDF = async () => {
    if (!jobId) return;
    setDownloading('pdf');
    try {
      const res = await fetch(`${API}/report/pdf/${jobId}`);
      if (!res.ok) throw new Error('PDF generation failed');
      const blob = await res.blob();
      downloadBlob(blob, `clipinsight_report_${jobId.slice(0, 8)}.pdf`);
    } catch (e) {
      console.error('PDF download error:', e);
    } finally {
      setDownloading(null);
    }
  };

  const handleShare = async () => {
    if (!jobId) return;
    try {
      const res = await fetch(`${API}/share/${jobId}`, { method: 'POST' });
      const data = await res.json();
      const shareUrl = `${window.location.origin}/shared/${data.token}`;
      await navigator.clipboard.writeText(shareUrl);
      setShareToast('🌸 Share link copied to clipboard!');
      setTimeout(() => setShareToast(''), 3000);
    } catch (e) {
      setShareToast('Could not create share link.');
      setTimeout(() => setShareToast(''), 3000);
    }
  };

  return (
    <div className="results-section">

      {/* Share toast notification */}
      {shareToast && (
        <div style={{
          position: 'fixed', top: 24, right: 24, zIndex: 9999,
          background: 'rgba(255,133,162,0.12)',
          border: '1px solid rgba(255,183,197,0.3)',
          backdropFilter: 'blur(16px)',
          borderRadius: 12, padding: '12px 20px',
          color: 'var(--text-primary)', fontSize: '0.9rem',
          boxShadow: '0 8px 32px rgba(255,133,162,0.15)',
          animation: 'fadeInDown 0.3s ease',
        }}>
          {shareToast}
        </div>
      )}

      {/* Header */}
      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 40, gap: 24, flexWrap: 'wrap' }}>
        <div>
          <div className="section-label">
            <div className="section-label-line" />
            <span>Analysis Report</span>
          </div>
          <h2 className="section-title">
            Your <span className="sakura-text">Insights</span><br />Have Bloomed
          </h2>
          <p style={{ color: 'var(--text-muted)', fontSize: '0.88rem', marginTop: 8 }}>
            桜の知恵 — Wisdom of the cherry blossom
          </p>
        </div>

        {/* Action buttons */}
        <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap', alignItems: 'center', marginTop: 8 }}>
          {/* Download Frames */}
          <button
            id="btn-download-frames"
            className="btn-ghost-sakura"
            onClick={handleDownloadFrames}
            disabled={downloading === 'frames' || !r.frames?.length}
            style={{ opacity: r.frames?.length ? 1 : 0.4, fontSize: '0.85rem', padding: '10px 18px' }}
          >
            {downloading === 'frames' ? '⏳ Zipping…' : '🖼 Frames ZIP'}
          </button>

          {/* Download PDF Report */}
          <button
            id="btn-download-pdf"
            className="btn-primary"
            onClick={handleDownloadPDF}
            disabled={downloading === 'pdf'}
            style={{ fontSize: '0.85rem', padding: '10px 18px' }}
          >
            {downloading === 'pdf' ? '⏳ Building PDF…' : '📑 Download PDF'}
          </button>

          {/* Share Link */}
          <button
            id="btn-share"
            className="btn-ghost-sakura"
            onClick={handleShare}
            style={{ fontSize: '0.85rem', padding: '10px 18px' }}
          >
            🔗 Share
          </button>

          {/* Text Report */}
          <button
            id="btn-download-report"
            className="btn-ghost-sakura"
            onClick={handleDownloadReport}
            style={{ fontSize: '0.85rem', padding: '10px 18px' }}
          >
            {downloading === 'report' ? '⏳ Saving…' : '📄 Text Report'}
          </button>

          {/* New Analysis */}
          <button className="btn-ghost-sakura" onClick={onReset} style={{ fontSize: '0.85rem', padding: '10px 18px' }}>
            ↩ New Analysis
          </button>
        </div>
      </div>

      {/* Stats row */}
      <div className="stat-row">
        {[
          { emoji: '⏱', label: 'Duration',    value: `${r.duration_seconds}s` },
          { emoji: '🖼', label: 'Frames',      value: r.frame_count },
          { emoji: '💬', label: 'Words',       value: r.word_count },
          { emoji: '🎯', label: 'Hook Score',  value: `${r.hook_score}/100` },
          { emoji: '😊', label: 'Sentiment',   value: r.sentiment },
        ].map(s => (
          <div key={s.label} className="stat-sakura">
            <div className="stat-emoji">{s.emoji}</div>
            <div className="stat-lbl">{s.label}</div>
            <div className="stat-val">{s.value}</div>
          </div>
        ))}
      </div>

      {/* Tabs */}
      <div className="results-tabs">
        {tabs.map(t => (
          <button
            key={t.key}
            className={`results-tab${tab === t.key ? ' active' : ''}`}
            onClick={() => setTab(t.key)}>
            {t.icon} {t.label}
          </button>
        ))}
      </div>

      {/* Content card */}
      <div className="glass-elevated" style={{
        borderRadius: 28, padding: '36px 40px',
        border: '1px solid rgba(255,183,197,0.1)',
        position: 'relative', overflow: 'hidden',
        minHeight: 340,
      }}>
        {/* Ghost kanji watermark */}
        <div style={{
          position: 'absolute', right: 24, top: '50%',
          transform: 'translateY(-50%)',
          fontFamily: 'var(--font-display)',
          fontSize: '8rem', fontWeight: 900,
          color: 'rgba(255,183,197,0.04)',
          pointerEvents: 'none', userSelect: 'none', lineHeight: 1,
        }}>
          {tabs.find(t => t.key === tab)?.kanji}
        </div>

        {/* ── SUMMARY ─────────────────────────────────────────────────────── */}
        {tab === 'summary' && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 28 }}>
            <p style={{ lineHeight: 1.9, fontSize: '1rem', color: 'var(--text-secondary)', maxWidth: 680 }}>
              {r.summary}
            </p>

            <div className="sakura-divider">
              <span>🌸</span>
            </div>

            {/* Tags */}
            <div>
              <div style={{ fontSize: '0.7rem', fontWeight: 600, letterSpacing: '0.15em', textTransform: 'uppercase', color: 'var(--text-muted)', marginBottom: 12 }}>
                Keywords & Tags
              </div>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8 }}>
                {(r.tags || []).map((tag: string) => (
                  <span key={tag} className="tag-chip">#{tag}</span>
                ))}
              </div>
            </div>

            {/* Target audience */}
            <div>
              <div style={{ fontSize: '0.7rem', fontWeight: 600, letterSpacing: '0.15em', textTransform: 'uppercase', color: 'var(--text-muted)', marginBottom: 12 }}>
                Target Audience
              </div>
              <div style={{
                display: 'inline-flex', alignItems: 'center', gap: 10,
                padding: '10px 20px', borderRadius: 12,
                background: 'rgba(255,183,197,0.06)',
                border: '1px solid rgba(255,183,197,0.15)',
                color: 'var(--sakura-blush)', fontSize: '0.9rem', fontWeight: 500,
              }}>
                🎯 {r.target_audience}
              </div>
            </div>

            {/* Referenced Media */}
            {r.referenced_media && (
              <div>
                <div style={{ fontSize: '0.7rem', fontWeight: 600, letterSpacing: '0.15em', textTransform: 'uppercase', color: 'var(--text-muted)', marginBottom: 12 }}>
                  🎬 Referenced Media (Movie / Series / Drama / Anime / Game)
                </div>
                <div style={{
                  display: 'inline-flex', alignItems: 'center', gap: 10,
                  padding: '10px 20px', borderRadius: 12,
                  background: 'rgba(255,183,197,0.06)',
                  border: '1px solid rgba(255,183,197,0.15)',
                  color: 'var(--sakura-blush)', fontSize: '0.9rem', fontWeight: 500,
                }}>
                  ✨ {r.referenced_media}
                </div>
              </div>
            )}
          </div>
        )}

        {/* ── INSIGHTS ────────────────────────────────────────────────────── */}
        {tab === 'insights' && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>
            {/* Hook Score */}
            <div>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 }}>
                <div style={{ fontSize: '0.7rem', fontWeight: 600, letterSpacing: '0.15em', textTransform: 'uppercase', color: 'var(--text-muted)' }}>
                  Hook Score — First 3 Seconds
                </div>
                <span style={{ fontFamily: 'var(--font-heading)', fontStyle: 'italic', fontSize: '1.5rem', color: 'var(--sakura-bloom)' }}>
                  {r.hook_score}<span style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>/100</span>
                </span>
              </div>
              <div className="hook-bar-track">
                <div className="hook-bar-fill" style={{ width: `${r.hook_score || 0}%` }} />
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: 6, fontSize: '0.72rem', color: 'var(--text-muted)' }}>
                <span>Weak</span><span>Average</span><span>Strong</span>
              </div>
            </div>

            {/* Sentiment */}
            <div>
              <div style={{ fontSize: '0.7rem', fontWeight: 600, letterSpacing: '0.15em', textTransform: 'uppercase', color: 'var(--text-muted)', marginBottom: 10 }}>
                Sentiment
              </div>
              <div style={{
                display: 'inline-flex', alignItems: 'center', gap: 8,
                padding: '8px 18px', borderRadius: 100,
                background: 'rgba(255,183,197,0.08)',
                border: '1px solid rgba(255,183,197,0.18)',
                fontSize: '0.9rem', fontWeight: 500, color: 'var(--sakura-pale)',
              }}>
                <span style={{ fontSize: '1.1rem' }}>
                  {r.sentiment === 'Positive' ? '😊' : r.sentiment === 'Negative' ? '😔' : '😐'}
                </span>
                {r.sentiment}
              </div>
            </div>

            <div className="sakura-divider"><span>🌸</span></div>

            {/* Suggestions */}
            <div>
              <div style={{ fontSize: '0.7rem', fontWeight: 600, letterSpacing: '0.15em', textTransform: 'uppercase', color: 'var(--text-muted)', marginBottom: 16 }}>
                Improvement Suggestions
              </div>
              {(r.suggestions || []).map((s: string, i: number) => (
                <div key={i} className="suggestion-item">
                  <div className="suggestion-num">{i + 1}</div>
                  <span style={{ fontSize: '0.9rem', color: 'var(--text-secondary)', lineHeight: 1.7 }}>{s}</span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* ── MUSIC ───────────────────────────────────────────────────────── */}
        {tab === 'music' && (
          <div>
            {r.music?.detected ? (
              <div style={{ display: 'flex', gap: 32, flexWrap: 'wrap', alignItems: 'flex-start' }}>
                {/* Cover art */}
                {r.music.cover_url && (
                  <div style={{
                    width: 140, height: 140, flexShrink: 0,
                    borderRadius: 16, overflow: 'hidden',
                    border: '1px solid rgba(255,183,197,0.2)',
                    boxShadow: '0 12px 40px rgba(232,85,122,0.25)',
                  }}>
                    <img
                      src={r.music.cover_url}
                      alt="Album cover"
                      style={{ width: '100%', height: '100%', objectFit: 'cover' }}
                    />
                  </div>
                )}

                {/* Song info */}
                <div style={{ flex: 1, minWidth: 200 }}>
                  <div style={{ fontSize: '0.7rem', fontWeight: 600, letterSpacing: '0.15em', textTransform: 'uppercase', color: 'var(--text-muted)', marginBottom: 8 }}>
                    {r.music.inferred ? '🌸 Music Inferred via AI Fallback' : '🎵 Music Identified via Shazam'}
                  </div>
                  <div style={{ fontSize: '1.6rem', fontFamily: 'var(--font-heading)', fontStyle: 'italic', color: 'var(--sakura-bloom)', marginBottom: 4, lineHeight: 1.2 }}>
                    {r.music.song_title}
                  </div>
                  <div style={{ fontSize: '1.05rem', color: 'var(--text-secondary)', marginBottom: 16 }}>
                    by {r.music.artist}
                  </div>

                  {r.music.inferred && (
                    <div style={{
                      padding: '12px 16px', borderRadius: 12, marginBottom: 16,
                      background: 'rgba(255,183,197,0.04)',
                      border: '1px solid rgba(255,183,197,0.12)',
                      fontSize: '0.85rem', lineHeight: 1.6, color: 'var(--text-secondary)'
                    }}>
                      <div style={{ fontWeight: 600, color: 'var(--sakura-blush)', marginBottom: 4, fontSize: '0.75rem', letterSpacing: '0.05em' }}>
                        AI CONFIDENCE: {Math.round((r.music.confidence || 0) * 100)}%
                      </div>
                      <span style={{ fontStyle: 'italic' }}>"{r.music.explanation}"</span>
                    </div>
                  )}

                  <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                    {r.music.album && (
                      <div style={{ display: 'flex', gap: 12, alignItems: 'center' }}>
                        <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)', minWidth: 52, letterSpacing: '0.1em' }}>ALBUM</span>
                        <span style={{ fontSize: '0.9rem', color: 'var(--sakura-pale)' }}>{r.music.album}</span>
                      </div>
                    )}
                    {r.music.genre && (
                      <div style={{ display: 'flex', gap: 12, alignItems: 'center' }}>
                        <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)', minWidth: 52, letterSpacing: '0.1em' }}>GENRE</span>
                        <span className="tag-chip">{r.music.genre}</span>
                      </div>
                    )}
                    {r.music.label && (
                      <div style={{ display: 'flex', gap: 12, alignItems: 'center' }}>
                        <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)', minWidth: 52, letterSpacing: '0.1em' }}>LABEL</span>
                        <span style={{ fontSize: '0.9rem', color: 'var(--sakura-pale)' }}>{r.music.label}</span>
                      </div>
                    )}
                  </div>

                  {r.music.apple_music_url && (
                    <a
                      href={r.music.apple_music_url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="btn-ghost-sakura"
                      style={{ display: 'inline-flex', alignItems: 'center', gap: 8, marginTop: 20, fontSize: '0.85rem', textDecoration: 'none' }}
                    >
                      🎧 Listen on Apple Music
                    </a>
                  )}
                </div>
              </div>
            ) : (
              <div style={{ textAlign: 'center', padding: '60px 0', color: 'var(--text-muted)' }}>
                <div style={{ fontSize: '4rem', marginBottom: 16 }}>🎵</div>
                <p style={{ fontFamily: 'var(--font-heading)', fontStyle: 'italic', fontSize: '1.1rem', marginBottom: 8 }}>
                  音楽は見つかりませんでした
                </p>
                <p style={{ fontSize: '0.85rem' }}>
                  {r.music?.reason || 'No music was detected in this video. It may be speech-only or silent.'}
                </p>
              </div>
            )}
          </div>
        )}

        {/* ── TRANSCRIPT ──────────────────────────────────────────────────── */}
        {tab === 'transcript' && (
          <div>
            {r.transcript ? (
              <div>
                <p style={{
                  lineHeight: 2, fontSize: '0.95rem',
                  color: 'var(--text-secondary)',
                  whiteSpace: 'pre-wrap',
                  maxHeight: 400, overflowY: 'auto',
                  paddingRight: 12,
                }}>
                  {r.transcript}
                </p>
              </div>
            ) : (
              <div style={{ textAlign: 'center', padding: '60px 0', color: 'var(--text-muted)' }}>
                <div style={{
                  fontSize: '4rem', marginBottom: 16,
                  filter: 'grayscale(0.3)',
                }}>🎙</div>
                <p style={{ fontFamily: 'var(--font-heading)', fontStyle: 'italic', fontSize: '1.1rem', marginBottom: 8 }}>
                  声はまだ沈黙の中に
                </p>
                <p style={{ fontSize: '0.85rem' }}>The transcript will appear after audio processing.</p>
              </div>
            )}
          </div>
        )}

        {/* ── FRAMES ──────────────────────────────────────────────────────── */}
        {tab === 'frames' && (
          <div>
            {r.frames && r.frames.length > 0 ? (
              <>
                <div style={{ display: 'flex', justifyContent: 'flex-end', marginBottom: 16 }}>
                  <button
                    className="btn-ghost-sakura"
                    onClick={handleDownloadFrames}
                    disabled={downloading === 'frames'}
                    style={{ fontSize: '0.82rem', padding: '8px 16px' }}
                  >
                    {downloading === 'frames' ? '⏳ Zipping…' : `🖼 Download All ${r.frames.length} Frames`}
                  </button>
                </div>
                <div style={{
                  display: 'grid',
                  gridTemplateColumns: 'repeat(auto-fill, minmax(160px, 1fr))',
                  gap: 14,
                }}>
                  {r.frames.map((frame: any, i: number) => (
                    <div key={i} style={{
                      borderRadius: 12, overflow: 'hidden',
                      border: '1px solid rgba(255,183,197,0.1)',
                      aspectRatio: '9/16',
                      background: 'rgba(255,183,197,0.04)',
                      cursor: 'pointer',
                      transition: 'all 0.3s ease',
                      position: 'relative',
                    }}
                      onClick={() => {
                        // Click to download individual frame
                        fetch(`${API}/frame/${frame.path}`)
                          .then(r => r.blob())
                          .then(blob => downloadBlob(blob, `frame_${i + 1}_at_${Math.round(frame.timestamp)}s.jpg`));
                      }}
                      onMouseEnter={e => {
                        e.currentTarget.style.transform = 'scale(1.04)';
                        e.currentTarget.style.borderColor = 'rgba(255,133,162,0.4)';
                        e.currentTarget.style.boxShadow = '0 8px 30px rgba(232,85,122,0.2)';
                      }}
                      onMouseLeave={e => {
                        e.currentTarget.style.transform = '';
                        e.currentTarget.style.borderColor = 'rgba(255,183,197,0.1)';
                        e.currentTarget.style.boxShadow = '';
                      }}>
                      <img
                        src={`${API}/frame/${frame.path}`}
                        alt={`Frame at ${frame.timestamp}s`}
                        loading="lazy"
                        style={{ width: '100%', height: '100%', objectFit: 'cover' }}
                      />
                      {/* Hover overlay with timestamp */}
                      <div style={{
                        position: 'absolute', bottom: 0, left: 0, right: 0,
                        padding: '6px 8px',
                        background: 'linear-gradient(transparent, rgba(0,0,0,0.6))',
                        fontSize: '0.7rem', color: 'rgba(255,255,255,0.7)',
                        textAlign: 'center',
                      }}>
                        {Math.round(frame.timestamp)}s · click to save
                      </div>
                    </div>
                  ))}
                </div>
              </>
            ) : (
              <div style={{ textAlign: 'center', padding: '60px 0', color: 'var(--text-muted)' }}>
                <div style={{ fontSize: '4rem', marginBottom: 16 }}>🎞</div>
                <p style={{ fontFamily: 'var(--font-heading)', fontStyle: 'italic', fontSize: '1.1rem', marginBottom: 8 }}>
                  映像はまだここにない
                </p>
                <p style={{ fontSize: '0.85rem' }}>Extracted frames will bloom here after video processing.</p>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
